# Generated by Django 5.0.6 on 2024-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, null=True)),
                ('teacher', models.CharField(max_length=90, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
