# Generated by Django 5.0.6 on 2024-05-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Java', 'java '), ('JS', 'javascript '), ('PY', 'python'), ('SQL', 'sql ')], max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Registered '), ('UR', 'unRegistered ')], max_length=90, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.user')),
                ('tag', models.ManyToManyField(to='bookstore.tag')),
            ],
        ),
    ]
