# Generated by Django 5.0.4 on 2024-05-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_coursecategory_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
