# Generated by Django 5.0.4 on 2024-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_remove_course_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_courses', to='bookstore.course'),
        ),
    ]
