# Generated by Django 5.0.4 on 2024-05-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_delete_coursecategory_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='bookstore.course'),
        ),
    ]
