# Generated by Django 5.0.4 on 2024-05-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_rename_username_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
